unbind-key -a
source-file ~/.config/tmux/tmux.reset.conf

bind-key -r f run-shell "tmux neww ~/bin/tmux-sessionizer"
bind-key -r r run-shell "~/bin/tmux-sessionizer"
bind-key -r p if-shell -F '#{==:#{session_name},popup}' {
   run-shell 'tmux kill-session -t popup' 
} {
    display-popup -d "#{pane_current_path}" -xC -yC -w 80% -h 75% -E 'tmux attach-session -t popup || tmux new-session -s popup'
}

set -g status-bg colour235
set -g status-fg white

